[package]
name = "YogurtSim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

# [[bin]]
# name = "YogurtSim"
# path = "src/main.rs"

[dependencies]
cfg-if = "1"
winit = "0.27"
env_logger = "0.9"
log = "0.4"
wgpu = "0.14"
pollster = "0.2"


[target.'cfg(target_arch = "wasm32")'.dependencies]
# make panic! to JS console
console_error_panic_hook = "0.1.6"
# log to JS console
console_log = "0.2.0"
# enable webgl feature on wgpu
wgpu = { version = "0.14", features = ["webgl"] }
# expose Rust methods that can be used in JS
wasm-bindgen = "0.2.76"
wasm-bindgen-futures = "0.4.30"
# bare minimum features for the web
web-sys = { version = "0.3.53", features = ["Document", "Window", "Element"] }

