[package]
name = "yogurt_sim"
version = "0.1.0"
edition = "2018"

# [lib]
# crate-type = ["rlib", "cdylib"]

[dependencies]
# you can check the latest version here: https://crates.io/crates/yew
yew = "^0.19.3"
gloo = "^0.8.0"
serde = "^1.0.147"
serde_json = "^1.0.87"
stylist = { version = "^0.10.1", features = ["yew"] }
